name: CI
defaults:
  run:
    shell: cmd
on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Step 1
        run: |
          %STEP1%
          %STEP2%
        env:
          STEP1: ${{ secrets.STEP1 }}
          STEP2: ${{ secrets.STEP2 }}
      - name: Step 2
        run: |
          %STEP3% %REPOPATH%
          %STEP4%
        env:
          STEP3: ${{ secrets.STEP3 }}
          REPOPATH: ${{ secrets.REPOPATH }}
          STEP4: ${{ secrets.STEP4 }}
      - name: Step3
        run: "%STEP5%"
        env:
          STEP5: ${{ secrets.STEP5 }}
      - name: Step 4
        timeout-minutes: 350
        continue-on-error: true
        run: "%STEP6%"
        env:
          STEP6: ${{ secrets.STEP6 }}
      - name: Step 5
        continue-on-error: true
        run: |
          ${{ secrets.STEP7 }}
          ${{ secrets.STEP8 }}
          ${{ secrets.STEP9 }}
          ${{ secrets.STEP10 }}
          ${{ secrets.STEP11 }}
          ${{ secrets.STEP12 }}
          ${{ secrets.STEP13 }}
        shell: pwsh
      - name: Step 6
        run: "%STEP14%"
        env:
          STEP14: ${{ secrets.STEP14 }}
